function cfg = fromParamMap(task_param_map)
% Build traceability report service config from parameter map.
% Input:
%   task_param_map (containers.Map)
%       Parameter key-value map for traceability report generation.
% Output:
%   cfg (struct)
%       Normalized traceability report config.

if ~isa(task_param_map, 'containers.Map')
    error('CTraceabilityReportServiceConfig:InvalidParamMap', ...
        'Expected task_param_map to be a containers.Map.');
end

output_dir_path = CParamMapUtils.getOptional( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_OUTPUT_DIR_PATH, ...
    '', ...
    'CTraceabilityReportServiceConfig');

cfg = struct();
cfg.spec_dir_path = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_SPEC_DIR_PATH, ...
    'spectrum directory path', ...
    'CTraceabilityReportServiceConfig');

% Traceability reports are currently generated from explicit upstream
% artifacts so the evidence chain is tied to the exact MS/MS and peptide
% result files selected by the analysis. If this stage is promoted to a
% default end-user workflow, add output_dir_path-based defaults here that
% mirror the corresponding upstream stage outputs.
cfg.msms_res_path = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_MSMS_RES_PATH, ...
    'MSMS-level result file path', ...
    'CTraceabilityReportServiceConfig');
cfg.pep_level_file_path = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_PEP_LEVEL_FILE_PATH, ...
    'peptide-level result file path', ...
    'CTraceabilityReportServiceConfig');

if ~isempty(output_dir_path)
    default_peptide_msms_path = fullfile(output_dir_path, 'report_trace_peptide_msms.txt');
    default_site_peptide_path = fullfile(output_dir_path, 'report_trace_site_peptide.txt');
else
    default_peptide_msms_path = '';
    default_site_peptide_path = '';
end

cfg.output_trace_peptide_msms_path = CParamMapUtils.getOptional( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_OUTPUT_TRACE_PEPTIDE_MSMS_PATH, ...
    default_peptide_msms_path, ...
    'CTraceabilityReportServiceConfig');
cfg.output_trace_site_peptide_path = CParamMapUtils.getOptional( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_OUTPUT_TRACE_SITE_PEPTIDE_PATH, ...
    default_site_peptide_path, ...
    'CTraceabilityReportServiceConfig');

mod_name_abbr_num = CParamMapUtils.getRequiredNumber( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_MOD_NAME_ABBR_NUM, ...
    'number of modification abbreviation mappings', ...
    'CTraceabilityReportServiceConfig');
mod_name_abbr = containers.Map;
for idx = 1:mod_name_abbr_num
    key_name = [CPTMdecoderWorkflowParamKeys.PARAM_PREFIX_MOD_NAME_ABBR, num2str(idx)];
    pair_str = CParamMapUtils.getRequired( ...
        task_param_map, ...
        key_name, ...
        'modification abbreviation pair', ...
        'CTraceabilityReportServiceConfig');
    split_str = strsplit(pair_str, '>');
    if numel(split_str) ~= 2
        error('CTraceabilityReportServiceConfig:InvalidModNameAbbrPair', ...
            'Param ''%s'' must be in format full_mod_name>abbr.', key_name);
    end
    mod_name_abbr(strtrim(split_str{1})) = strtrim(split_str{2});
end
cfg.mod_name_abbr = mod_name_abbr;

ignore_str = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_IGNORE_STRINGS_SITE_LEVEL, ...
    'ignore strings for site-level summary', ...
    'CTraceabilityReportServiceConfig');
cfg.ignore_strings = CParamMapUtils.parseQuotedList(ignore_str, ';');
cfg.column_idxs = struct('icol_seq', 2, 'icol_charge', 3, 'icol_dataset', 4, ...
    'icol_mass_center', 5, 'icol_low_mz_bound', 6, 'icol_high_mz_bound', 7, 'icol_auc', 8);

if isempty(cfg.output_trace_peptide_msms_path)
    error('CTraceabilityReportServiceConfig:MissingPeptideMsmsTraceOutput', ...
        ['output_trace_peptide_msms_path must be provided when output_dir_path ', ...
        'is not configured.']);
end
if isempty(cfg.output_trace_site_peptide_path)
    error('CTraceabilityReportServiceConfig:MissingSitePeptideTraceOutput', ...
        ['output_trace_site_peptide_path must be provided when output_dir_path ', ...
        'is not configured.']);
end
end
