classdef CFdrFilteredResult
    properties
        entries
    end

    methods
        function obj = CFdrFilteredResult(entries)
            if nargin < 1
                entries = CFdrFilteredResult.emptyEntries();
            end
            obj.entries = entries;
        end

        function n = count(obj)
            n = numel(obj.entries);
        end
    end

    methods (Static)
        function entries = emptyEntries()
            entries = struct( ...
                'Site', {}, ...
                'DatasetName', {}, ...
                'Scan', {}, ...
                'Spectrum', {}, ...
                'Charge', {}, ...
                'Calc_neutral_pepmass', {}, ...
                'precursor_neutral_mass', {}, ...
                'massdiff', {}, ...
                'num_match_ions', {}, ...
                'peptide', {}, ...
                'protein', {}, ...
                'modification', {}, ...
                'modificationlocation', {}, ...
                'Score', {} ...
            );
        end
    end
end
