function helper_test_quant_norm_pep(projectRootDir, testDataDir, outputDir)
% HELPER_TEST_QUANT_NORM_PEP Runs the quant normalization peptide test case
% Input:
%   projectRootDir (1 x 1 char/string) - root of the codebase
%   testDataDir (1 x 1 char/string) - directory containing test data (e.g., .../code/test/data)
%   outputDir (1 x 1 char/string) - directory to write outputs
% Output:
%   (none)

    % --- Configuration ---
    result_dir = fullfile(outputDir, 'requant_norm_pep');
    input_dir = fullfile(testDataDir, 'requant_norm_pep');
    
    peptide_list = {
        'AGLQFPVGR','VTIAQGGVLPNIQAVLLPK',...
        'LLLPGELAK','EIQTAVR',...
        'STELLIR','EIAQDFK',...
        'TLYGFGG','VFLENVIR','ISGLIYEETR'
    };
    prot_list = {
        'H2A','H2A',...
        'H2B','H2B',...
        'H3','H3',...
        'H4','H4','H4'
    };
    experimentNames = {''};
    ms1_tolerance.value = 10;
    ms1_tolerance.isppm = 1;
    resFilterThres = 0.1;
    alpha = 0.01;

    mod_file = fullfile(projectRootDir, 'modify.ini');
    outputPath = fullfile(result_dir, experimentNames{1});
    specPath = fullfile(input_dir, experimentNames{1});

    processor = CMSMSPepDeconv( ...
        mod_file, ...
        '', '', ...
        specPath, ...
        ms1_tolerance, ...
        0.02, ...
        alpha, ...
        '', '', ...
        '', ...
        1, 2, 0.5, resFilterThres, ...
        {}, ...
        outputPath, ...
        [1,2], ...
        fullfile(input_dir, 'peptide4normalization_checked.txt'), ...
        '', ...
        fullfile(input_dir, 'filtered_result_mascot.txt') ...
    );

    processor.quant_norm_pep_from_fdr( ...
        peptide_list, prot_list, ...
        fullfile(input_dir, 'filtered_result_mascot.txt'), ...
        'peptide4normalization.txt' ...
    );
    processor.requant_norm_pep();
end