function helper_test_quant_norm_pep(~, testDataDir, outputDir)
% HELPER_TEST_QUANT_NORM_PEP Runs the quant normalization peptide test case
% Input:
%   projectRootDir (1 x 1 char/string) - root of the codebase
%   testDataDir (1 x 1 char/string) - directory containing test data (e.g., .../code/test/data)
%   outputDir (1 x 1 char/string) - directory to write outputs
% Output:
%   (none)

    % --- Configuration ---
    result_dir = fullfile(outputDir, 'requant_norm_pep');
    input_dir = fullfile(testDataDir, 'requant_norm_pep');

    pair_file_path = fullfile(input_dir, 'norm_protein_peptide.tsv');
    [prot_list, peptide_list] = CProteinPeptidePairFileReader.readPairFile(pair_file_path);
    if numel(prot_list) ~= numel(peptide_list)
        error('helper_test_quant_norm_pep:PairLengthMismatch', ...
            ['Parsed pair file has inconsistent lengths: prot_list=%d, peptide_list=%d. ', ...
             'Please check delimiter and file content: %s'], ...
            numel(prot_list), numel(peptide_list), pair_file_path);
    end
    ms1_tolerance.value = 10;
    ms1_tolerance.isppm = 1;
    resFilterThres = 0.1;
    alpha = 0.01;

    % Build one shared minimal config consumed by both normalization services.
    msms_cfg = struct( ...
        'spec_dir_path', input_dir, ...
        'ms1_tolerance', ms1_tolerance, ...
        'alpha', alpha, ...
        'result_filter_threshold', resFilterThres, ...
        'output_dir_path', result_dir, ...
        'checked_peptides_res_path', fullfile(input_dir, 'peptide4normalization_checked.txt'), ...
        'min_MSMS_num', 1 ...
    );

    norm_quant_cfg = struct( ...
        'msms_cfg', msms_cfg, ...
        'peptide_list', {peptide_list}, ...
        'prot_list', {prot_list}, ...
        'filtered_res_file_path', fullfile(input_dir, 'filtered_result_mascot.txt'), ...
        'output_file_name', 'peptide4normalization.txt' ...
    );
    quant_service = CNormalizationQuantService(norm_quant_cfg);
    quant_service.run();

    norm_requant_cfg = struct( ...
        'msms_cfg', msms_cfg, ...
        'output_file_name', 'peptide4normalization_requant.txt' ...
    );
    requant_service = CNormalizationRequantService(norm_requant_cfg);
    requant_service.run();
end