function helper_test_auto_align_quant(projectRootDir, testDataDir, outputDir)
% HELPER_TEST_AUTO_ALIGN_QUANT Runs the auto align quant test case
% Input:
%   projectRootDir (1 x 1 char/string) - root of the codebase
%   testDataDir (1 x 1 char/string) - directory containing test data (e.g., .../code/test/data)
%   outputDir (1 x 1 char/string) - directory to write outputs
% Output:
%   (none)

    % --- Configuration ---
    result_dir = fullfile(outputDir, 'auto_align_quant');
    input_dir = fullfile(testDataDir, 'auto_align_quant');
    
    ms1_tolerance.value = 10;
    ms1_tolerance.isppm = 1;
    resFilterThres = 0.1;
    alpha = 0.01;

    mod_file = fullfile(projectRootDir, 'modify.ini');
    fixed_mod = '';
    variable_mod = 'Acetyl[K];Methyl[K];Dimethyl[K];Trimethyl[K]';
    enzyme.name = 'trypsin';
    enzyme.limits = 14.015650;

    align_requant_service = CPeptideAlignRequantService( ...
        mod_file, ...
        fixed_mod, variable_mod, ...
        input_dir, ...
        ms1_tolerance, ...
        0.02, ...
        alpha, ...
        fullfile(input_dir,'uniprotkb_human_histone_E_coli_comb_rever_czy_20231015.fasta'), '>([^ ,]*)', ...
        fullfile(input_dir, 'pepSpecFile.txt'), ...
        1, 2, 0.5, resFilterThres, ...
        enzyme, ...
        result_dir, ...
        [1,2], ...
        [], ...
        fullfile(input_dir, 'report_msms.txt'), ...
        fullfile(input_dir, 'filtered_result_mascot.txt') ...
    );
    
    pairs = { ...
        'MCF7_JIB04_2_HISTONE_0723_HCDFT.mgf', 'MCF7_DMSO_2_HISTONE_0723_HCDFT.mgf'; ...
    };

    strategy = PairwiseRunAlignStrategy(pairs);
    align_options = struct('min_psm', 1, 'rt_sigma', 0.5, 'outlier_k', 3, ...
        'outlier_method', 'mad', 'dead_time_min', 0.5);
    align_requant_service.run(strategy, align_options);
end