function tests = test_CMS2SpectrumPipeline
% TEST_CMS2SPECTRUMPIPELINE Test script for CMS2SpectrumPipeline construction and failure behavior
% Input:
%   (none)
% Output:
%   tests (matlab.unittest.Test)

tests = functiontests(localfunctions);
end

function testConstructWithConfig(testCase)
% TESTCONSTRUCTWITHCONFIG Validate cfg-mode constructor assigns key fields correctly
% Input:
%   testCase (matlab.unittest.TestCase)
% Output:
%   (none)

cfg = CMS2SpectrumPipelineConfig(struct( ...
    'model', 2, ...
    'method', 1, ...
    'lambda', 0.1, ...
    'ms1_tolerance', struct('value', 10, 'isppm', true), ...
    'ms2_tolerance', 0.02, ...
    'alpha', 0.2, ...
    'resFilterThres', 0.05, ...
    'ionTypes', [1,2], ...
    'enzyme', struct('name', 'Trypsin', 'limits', [1 0]), ...
    'case_penalty_intens', 'intens_sum', ...
    'grid_penalty_intens', 'intens_sum', ...
    'case_OLS_intens_weight', 'none'));

obj = CMS2SpectrumPipeline( ...
    containers.Map('KeyType','char','ValueType','double'), ...
    containers.Map('KeyType','char','ValueType','double'), ...
    cfg);

testCase.verifyEqual(obj.m_model, 2);
testCase.verifyEqual(obj.m_method, 1);
testCase.verifyEqual(obj.m_alpha, 0.2, 'AbsTol', 1e-12);
testCase.verifyEqual(obj.m_resFilterThres, 0.05, 'AbsTol', 1e-12);
end

function testRunBaselineSpectrumStageExceptionPropagates(testCase)
%  Validate runBaselineSpectrumStage propagates runtime exception to caller
% Input:
%   testCase (matlab.unittest.TestCase)
% Output:
%   (none)

cfg = CMS2SpectrumPipelineConfig(struct( ...
    'model', 2, ...
    'method', 1, ...
    'lambda', 0.1, ...
    'ms1_tolerance', struct('value', 10, 'isppm', true), ...
    'ms2_tolerance', 0.02, ...
    'alpha', 0.2, ...
    'resFilterThres', 0.05, ...
    'ionTypes', [1,2], ...
    'enzyme', struct('name', 'Trypsin', 'limits', [1 0]), ...
    'case_penalty_intens', 'intens_sum', ...
    'grid_penalty_intens', 'intens_sum', ...
    'case_OLS_intens_weight', 'none'));

% Intentionally provide invalid spectrum context to trigger runtime exception
obj = CMS2SpectrumPipeline( ...
    containers.Map('KeyType','char','ValueType','double'), ...
    containers.Map('KeyType','char','ValueType','double'), ...
    cfg);

peptideCtx = struct( ...
    'pepSeq', 'PEPTIDE', ...
    'isProtN', true, ...
    'isProtC', false, ...
    'fixedModNameMass', {containers.Map('KeyType','char','ValueType','double')}, ...
    'variableModNameMass', {containers.Map('KeyType','char','ValueType','double')});

spectrumCtx = struct( ...
    'datasetName', 'rawA', ...
    'specName', 'specA', ...
    'expPeaks', [], ...
    'iCharge', [], ...
    'precursorMZ', []);

testCase.verifyError(@() obj.runBaselineSpectrumStage(peptideCtx, spectrumCtx), ...
    'MATLAB:Containers:Map:IncorrectIndexing');
end
