function tests = test_CMS2SpectrumPipeline
% TEST_CMS2SPECTRUMPIPELINE Test script for CMS2SpectrumPipeline construction and failure behavior
% Input:
%   (none)
% Output:
%   tests (matlab.unittest.Test)

tests = functiontests(localfunctions);
end

function testConstructWithConfig(testCase)
% TESTCONSTRUCTWITHCONFIG Validate cfg-mode constructor assigns key fields correctly
% Input:
%   testCase (matlab.unittest.TestCase)
% Output:
%   (none)

cfg = CMS2SpectrumPipelineConfig(struct( ...
    'model', 2, ...
    'method', 1, ...
    'lambda', 0.1, ...
    'ms1_tolerance', struct('value', 10, 'isppm', true), ...
    'ms2_tolerance', 0.02, ...
    'alpha', 0.2, ...
    'resFilterThres', 0.05, ...
    'ionTypes', [1,2], ...
    'enzyme', struct('name', 'Trypsin', 'limits', [1 0]), ...
    'case_penalty_intens', 'intens_sum', ...
    'grid_penalty_intens', 'intens_sum', ...
    'case_OLS_intens_weight', 'none'));

obj = CMS2SpectrumPipeline('PEPTIDE', true, false, [], 'rawA', 'specA', ...
    containers.Map('KeyType','char','ValueType','double'), ...
    containers.Map('KeyType','char','ValueType','double'), cfg);

testCase.verifyEqual(obj.m_model, 2);
testCase.verifyEqual(obj.m_method, 1);
testCase.verifyEqual(obj.m_alpha, 0.2, 'AbsTol', 1e-12);
testCase.verifyEqual(obj.m_resFilterThres, 0.05, 'AbsTol', 1e-12);
end

function testProcessSpectrumCatchPath(testCase)
% TESTPROCESSSPECTRUMCATCHPATH Validate processSpectrum returns safe failure payload on runtime exception
% Input:
%   testCase (matlab.unittest.TestCase)
% Output:
%   (none)

cfg = CMS2SpectrumPipelineConfig(struct( ...
    'model', 2, ...
    'method', 1, ...
    'lambda', 0.1, ...
    'ms1_tolerance', struct('value', 10, 'isppm', true), ...
    'ms2_tolerance', 0.02, ...
    'alpha', 0.2, ...
    'resFilterThres', 0.05, ...
    'ionTypes', [1,2], ...
    'enzyme', struct('name', 'Trypsin', 'limits', [1 0]), ...
    'case_penalty_intens', 'intens_sum', ...
    'grid_penalty_intens', 'intens_sum', ...
    'case_OLS_intens_weight', 'none'));

% Intentionally provide invalid dataset IO to trigger try/catch path
obj = CMS2SpectrumPipeline('PEPTIDE', true, false, struct(), 'rawA', 'specA', ...
    containers.Map('KeyType','char','ValueType','double'), ...
    containers.Map('KeyType','char','ValueType','double'), cfg);

[bSuccess,cstrIMP,abundance,ionTypePosCharge,ionIntens,frageff,warning_msg,is_X_not_full_column_rank] = obj.processSpectrum();

testCase.verifyFalse(bSuccess);
testCase.verifyEmpty(cstrIMP);
testCase.verifyEmpty(abundance);
testCase.verifyEmpty(ionTypePosCharge);
testCase.verifyEmpty(ionIntens);
testCase.verifyEmpty(frageff);
testCase.verifyFalse(is_X_not_full_column_rank);
testCase.verifyNotEmpty(warning_msg);
testCase.verifyTrue(contains(char(warning_msg), '[CMS2]'));
end
