function imp_records = onGroupQuant(obj, imp_records, group)
% Append quantification records for a single group
% Input:
%   obj (CIMPProcessingExecutor)
%       processing executor instance
%   imp_records (CIMPQuantRecord array)
%       accumulator for IMP records
%   group (CIMPGroup)
%       group payload for one raw and charge
% Output:
%   imp_records (CIMPQuantRecord array)
%       updated accumulator

[has_nonzero_imp, imp_idx_nonzero, area_imp_final, xic_peak_rt_bounds, idx_selected, ratio_each_XIC_peak, diagnostics] = ...
    CIMPQuantCore.quantGroup(obj.m_ms12DatasetIO, group.rawName,...
    group.ratio(group.chargeGroupIdxs,:),...
    group.rts(group.chargeGroupIdxs,:),...
    group.intensity(group.chargeGroupIdxs,:),...
    group.lowMzBound, group.highMzBound, group.selectedCharge,...
    obj.m_minMSMSnum, obj.m_alpha, obj.m_resFilterThres, obj.m_minXicNonzeroPoints);

CIMPQuantStats.quant_group_stats('record', diagnostics);
if diagnostics.filtered_sparse_peak_count > 0
    if diagnostics.filtered_sparse_peak_count == diagnostics.candidate_peak_count
        event_name = 'All sparse peaks filtered';
    else
        event_name = 'Partial sparse peak filter';
    end
    CLogger.debug(['[CIMPProcessingExecutor:onGroupQuant] %s. raw=%s, charge=%d, ', ...
        'imps=%s, reason=%s, candidate_peak_count=%d, filtered_sparse_peak_count=%d, ', ...
        'candidate_nonzero_points=%s.'], ...
        event_name, ...
        group.rawName, group.selectedCharge, strjoin(group.impNames, ';'), diagnostics.reason, ...
        diagnostics.candidate_peak_count, diagnostics.filtered_sparse_peak_count, ...
        mat2str(diagnostics.candidate_nonzero_points'));
end

if ~has_nonzero_imp
    return;
end
for i_imp = 1:length(imp_idx_nonzero)
    rt_peaks = repmat(struct('rt_start',0,'rt_end',0,'ratio',0,'check_label',0), 0, 1);
    for i_peak = 1:size(xic_peak_rt_bounds,2)
        if ratio_each_XIC_peak(i_imp,i_peak) == 0
            continue;
        end
        if i_peak == idx_selected(i_imp)
            check_label = 1;
        else
            check_label = 0;
        end
        rt_peaks(end+1,1) = struct(...
            'rt_start', xic_peak_rt_bounds(i_imp,i_peak).rt_start, ...
            'rt_end', xic_peak_rt_bounds(i_imp,i_peak).rt_end, ...
            'ratio', ratio_each_XIC_peak(i_imp,i_peak), ...
            'check_label', check_label); %#ok<AGROW>
    end
    imp_records(end+1,1) = CIMPQuantRecord(...
        group.impNames{imp_idx_nonzero(i_imp)}, ...
        group.selectedCharge, ...
        group.rawName, ...
        mean([group.lowMzBound, group.highMzBound]), ...
        group.lowMzBound, ...
        group.highMzBound, ...
        area_imp_final(i_imp,1), ...
        rt_peaks); %#ok<AGROW>
end
end
