classdef CMSMSPepDeconv
    properties
        m_modFile;          % Modification file path
        m_specPath;         % Path to the mixed spectra MGF file
        m_ms1_tolerance;    % Tolerance of MS1
        m_ms2_tolerance;    % Fragment ion matching tolerance
        m_alpha;            % Threshold for filtering noise peaks
        m_fastaFile;        % Absolute path to the FASTA file
        m_regular_express;  % The regular expression used for parsing protein name
        m_pepSpecFile;      % Input file name specifying some sequences and their corresponding spectra names
        m_filtered_res_file_path; % Input file name specifying FDR filtered PSM results
        m_model;            % Three models generated by three fragmentation efficiency assumptions: variable efficiency, constant but unequal efficiency, and efficiency of 1
        m_method;           % Estimation method, either ordinary least squares or with LASSO penalty
        m_lambda;           % LASSO penalty parameter
        m_resFilterThres;   % Threshold for filtering results by relative intensity
        m_enzyme;           % Enzyme used for digestion
        m_outputDir;        % Output folder
        m_checked_peptides_res_path; % File path for manually checked peptide results
        m_msms_res_path;    % File path for MSMS results
        m_min_MSMS_num;     % Minimum number of deconvoluted MSMS spectra for a peptide to be considered
        m_ionTypes;         % Ion types used for matching

        m_case_penalty_intens; % penalty intensity mode for SDP/KSDP/hyperscore
        m_grid_penalty_intens; % penalty intensity mode inside KSDP grid
        m_case_OLS_intens_weight; % OLS intensity weighting mode for X matrix

        m_fixedModNameMass;     % Specified fixed modifications: name, specificity, and mass
        m_variableModNameMass;  % Specified variable modifications: name, specificity, and mass
        m_cMgfDatasetIO;        % Record MGF spectra
        m_cMs12DatasetIO;       % Record MS1 and MS2 spectra
        CPepProtService;             % Record protein sequences database

        m_cMsFileMapper;    % Handle to CMsFileMapper for MGF<->MS1 mapping
        
        m_matFragInfo;      % Information of ions, three columns represent [b/y type, position, charge], each row is a fragment ion
        m_matFragEff;       % Fragmentation efficiency matrix of ions, each row corresponds to m_matFragInfo, each column is a solvable MS2 spectrum
        m_matFragIntens;    % Sum of experimental peak intensities of ions, each row corresponds to m_matFragInfo, each column is a solvable MS2 spectrum
    end

    methods
        function obj = CMSMSPepDeconv(modFile_or_taskparamobj,fixedMod,variableMod,...
            specPath,ms1_tolerance,ms2_tolerance,alpha,...
            fastaFile,regular_express,pepSpecFile,model,method,lambda,...
            resFilterThres,enzyme,outputDir,ionTypes,checked_peptides_res_path,msms_res_path,filtered_res_file_path)
            % Input (single arg):
            %   modFile_or_taskparamobj (CTaskParam)
            %       task parameter object
            % Input (full args):
            %   modFile_or_taskparamobj (1 x 1 char/string)
            %       modification file path
            %   fixedMod (1 x 1 char/string)
            %       fixed modification specification
            %   variableMod (1 x 1 char/string)
            %       variable modification specification
            %   specPath (1 x 1 char/string)
            %       spectrum directory path
            %   ms1_tolerance (struct)
            %       MS1 tolerance (fields: value, isppm)
            %   ms2_tolerance (struct)
            %       MS2 tolerance (fields: value, isppm)
            %   alpha (1 x 1 double)
            %       noise filtering threshold factor
            %   fastaFile (1 x 1 char/string)
            %       FASTA file path
            %   regular_express (1 x 1 char/string)
            %       regex for protein name parsing
            %   pepSpecFile (1 x 1 char/string)
            %       peptide-spectrum list file path
            %   model (1 x 1 double/int)
            %       model index
            %   method (1 x 1 double/int or char/string)
            %       estimation method
            %   lambda (1 x 1 double)
            %       LASSO penalty parameter
            %   resFilterThres (1 x 1 double)
            %       result filter threshold
            %   enzyme (struct)
            %       enzyme settings
            %   outputDir (1 x 1 char/string)
            %       output directory
            %   ionTypes (1 x T double/int, optional)
            %       ion types for matching
            %   checked_peptides_res_path (1 x 1 char/string, optional)
            %       checked peptide results path
            %   msms_res_path (1 x 1 char/string, optional)
            %       MSMS results path
            %   filtered_res_file_path (1 x 1 char/string, optional)
            %       filtered PSM results path
            if nargin == 1
                % This is a method to read parameters from a .param file
                taskParam = modFile_or_taskparamobj;
                obj.m_specPath = taskParam.m_spec_dir_path;
                obj.m_modFile = taskParam.m_mod_file_path;
                obj.m_fastaFile = taskParam.m_fasta_file_path;
                obj.m_regular_express = taskParam.m_regular_express;
                obj.m_pepSpecFile = taskParam.m_pep_spec_file_path;
                obj.m_filtered_res_file_path = taskParam.m_filtered_res_file_path;
                obj.m_outputDir = taskParam.m_output_dir_path;
                obj.m_model = taskParam.m_model;
                obj.m_method = taskParam.m_method;
                obj.m_lambda = taskParam.m_lambda;
                obj.m_ms1_tolerance = taskParam.m_ms1_tolerance;
                obj.m_ms2_tolerance = taskParam.m_ms2_tolerance;
                obj.m_alpha = taskParam.m_alpha;
                obj.m_resFilterThres = taskParam.m_result_filter_threshold;
                obj.m_ionTypes = [1,2];
                obj.m_enzyme.name = taskParam.m_enzyme_name;
                obj.m_enzyme.limits = taskParam.m_enzyme_limits;
                obj.m_checked_peptides_res_path = taskParam.m_checked_peptides_res_path;
                obj.m_msms_res_path = taskParam.m_msms_res_path;
                obj.m_min_MSMS_num = taskParam.m_min_MSMS_num;
                fixedMod = taskParam.m_fixed_mod;
                variableMod = taskParam.m_variable_mod;

                obj.m_case_penalty_intens = 'intens_sum';
                obj.m_grid_penalty_intens = 'intens_sum';
                obj.m_case_OLS_intens_weight = 'none';
            else
                obj.m_specPath = specPath;
                obj.m_modFile = modFile_or_taskparamobj;
                obj.m_fastaFile = fastaFile;
                obj.m_regular_express = regular_express;
                obj.m_pepSpecFile = pepSpecFile;
                obj.m_model = model;
                obj.m_method = method;
                obj.m_lambda = lambda;
                obj.m_ms1_tolerance = ms1_tolerance;
                obj.m_ms2_tolerance = ms2_tolerance;
                obj.m_alpha = alpha;
                obj.m_resFilterThres = resFilterThres;
                obj.m_enzyme = enzyme;
                obj.m_outputDir = outputDir;
                obj.m_min_MSMS_num = 1;
                obj.m_case_penalty_intens = 'intens_sum';
                obj.m_grid_penalty_intens = 'intens_sum';
                obj.m_case_OLS_intens_weight = 'none';
                if nargin >= 17
                    obj.m_ionTypes = ionTypes;
                end
                if nargin >= 18
                    obj.m_checked_peptides_res_path = checked_peptides_res_path;
                end
                if nargin >= 19
                    obj.m_msms_res_path = msms_res_path;
                end
                if nargin >= 20
                    obj.m_filtered_res_file_path = filtered_res_file_path;
                end
            end

            % Generate variable modification "name-mass" dictionary using user-specified target modification strings and modification library
            mapModification = readModifyInfo(obj.m_modFile);
            obj.m_fixedModNameMass = obj.getModMassName(fixedMod,mapModification);
            obj.m_variableModNameMass = obj.getModMassName(variableMod,mapModification);
            
            % Ensure file mapper is initialized
            if isempty(obj.m_cMsFileMapper)
                obj.m_cMsFileMapper = CMsFileMapper(obj.m_specPath);
            end
        end

        % Run at MSMS level and peptide level
        obj = startRun(obj, is_record_fragment_information)

        % Generate modification "name-mass" list from user settings
        [modNameMass] = getModMassName(obj,modificationTypes,mapModification)

        % Re-quantify the IMPs using checked XIC peaks
        obj = requant(obj)

        % Re-quantify the normalization peptides using checked XIC peaks
        obj = requant_norm_pep(obj)

        % Draw the XIC for gathered peptides using manually-checked rt range, to dir_save
        % The color_map and legend_map are optional
        drawXIC(obj, dir_save, color_map, legend_map);
    end

    methods (Access=private)
        function block = buildQuantBlock(obj, prot_names_pos, rawManager)
            imp_records = CIMPQuantRecord.empty(0,1);
            [raw_names, raw_ident_stores] = rawManager.getEntries();
            groupAggregator = CIMPGroupAggregator(obj.m_ms1_tolerance);
            imp_records = groupAggregator.aggregate(raw_names, raw_ident_stores, [], ...
                @(state, group) obj.appendQuantGroupRecord(state, group), imp_records);
            if isempty(imp_records)
                block = CIMPQuantBlock.empty(0,1);
            else
                block = CIMPQuantBlock(prot_names_pos, imp_records);
            end
        end

        function block = buildRequantBlock(obj, prot_names_pos, rawManager, pep_rtrange_map)
            imp_records = CIMPQuantRecord.empty(0,1);
            [raw_names, raw_ident_stores] = rawManager.getEntries();
            groupAggregator = CIMPGroupAggregator(obj.m_ms1_tolerance);
            imp_records = groupAggregator.aggregate(raw_names, raw_ident_stores, pep_rtrange_map, ...
                @(state, group) obj.appendRequantGroupRecord(state, group), imp_records);
            if isempty(imp_records)
                block = CIMPQuantBlock.empty(0,1);
            else
                block = CIMPQuantBlock(prot_names_pos, imp_records);
            end
        end

        function drawImpXic(obj, rawManager, pep_rtrange_map, dir_save, color_map, legend_map)
            state = struct('dir_save', dir_save, 'color_map', color_map, 'legend_map', legend_map);
            [raw_names, raw_ident_stores] = rawManager.getEntries();
            groupAggregator = CIMPGroupAggregator(obj.m_ms1_tolerance);
            groupAggregator.aggregate(raw_names, raw_ident_stores, pep_rtrange_map, ...
                @(state_in, group) obj.drawGroupXic(state_in, group), state);
        end

        function imp_records = appendQuantGroupRecord(obj, imp_records, group)
            [has_nonzero_imp, imp_idx_nonzero, area_imp_final, xic_peak_rt_bounds, idx_selected, ratio_each_XIC_peak] = ...
                CIMPQuantifier.quantGroup(obj.m_cMs12DatasetIO, group.rawName,...
                group.ratio(group.chargeGroupIdxs,:),...
                group.rts(group.chargeGroupIdxs,:),...
                group.intensity(group.chargeGroupIdxs,:),...
                group.lowMzBound, group.highMzBound, group.selectedCharge,...
                obj.m_min_MSMS_num, obj.m_alpha, obj.m_resFilterThres);

            if ~has_nonzero_imp
                return;
            end
            for i_iso = 1:length(imp_idx_nonzero)
                rt_peaks = repmat(struct('rt_start',0,'rt_end',0,'ratio',0,'check_label',0), 0, 1);
                for i_peak = 1:size(xic_peak_rt_bounds,2)
                    if ratio_each_XIC_peak(i_iso,i_peak) == 0
                        continue;
                    end
                    if i_peak == idx_selected(i_iso)
                        check_label = 1;
                    else
                        check_label = 0;
                    end
                    rt_peaks(end+1,1) = struct(...
                        'rt_start', xic_peak_rt_bounds(i_iso,i_peak).rt_start, ...
                        'rt_end', xic_peak_rt_bounds(i_iso,i_peak).rt_end, ...
                        'ratio', ratio_each_XIC_peak(i_iso,i_peak), ...
                        'check_label', check_label); %#ok<AGROW>
                end
                imp_records(end+1,1) = CIMPQuantRecord(...
                    group.impNames{imp_idx_nonzero(i_iso)}, ...
                    group.selectedCharge, ...
                    group.rawName, ...
                    mean([group.lowMzBound, group.highMzBound]), ...
                    group.lowMzBound, ...
                    group.highMzBound, ...
                    area_imp_final(i_iso,1), ...
                    rt_peaks); %#ok<AGROW>
            end
        end

        function imp_records = appendRequantGroupRecord(obj, imp_records, group)
            if isempty(group.impRtRanges) || all(cellfun(@isempty, group.impRtRanges))
                return;
            end

            [has_nonzero_imp, imp_idx_nonzero, area_imp_final, xic_peak_rt_bounds, max_label, ratio_each_XIC_peak] = ...
                CIMPQuantifier.requantGroup(obj.m_cMs12DatasetIO, group.rawName,...
                group.ratio(group.chargeGroupIdxs,:),...
                group.rts(group.chargeGroupIdxs,:),...
                group.intensity(group.chargeGroupIdxs,:),...
                group.lowMzBound, group.highMzBound, ...
                group.selectedCharge, group.impRtRanges,...
                obj.m_min_MSMS_num);

            if ~has_nonzero_imp
                return;
            end
            for i_iso = 1:length(imp_idx_nonzero)
                rt_peaks = struct(...
                    'rt_start', xic_peak_rt_bounds(i_iso).rt_start, ...
                    'rt_end', xic_peak_rt_bounds(i_iso).rt_end, ...
                    'ratio', ratio_each_XIC_peak(i_iso), ...
                    'check_label', max_label(i_iso));
                imp_records(end+1,1) = CIMPQuantRecord(...
                    group.impNames{imp_idx_nonzero(i_iso)}, ...
                    group.selectedCharge, ...
                    group.rawName, ...
                    mean([group.lowMzBound, group.highMzBound]), ...
                    group.lowMzBound, ...
                    group.highMzBound, ...
                    area_imp_final(i_iso,1), ...
                    rt_peaks); %#ok<AGROW>
            end
        end

        function state = drawGroupXic(obj, state, group)
            if isempty(group.impRtRanges) || all(cellfun(@isempty, group.impRtRanges))
                return;
            end

            CIMPQuantPlotter.drawGroup(obj.m_cMs12DatasetIO, obj.m_min_MSMS_num, group.rawName, ...
                group.ratio(group.chargeGroupIdxs,:), ...
                group.rts(group.chargeGroupIdxs,:), ...
                group.intensity(group.chargeGroupIdxs,:), ...
                group.lowMzBound, group.highMzBound, ...
                group.selectedCharge, group.impRtRanges, ...
                group.impNames, state.dir_save, state.color_map, state.legend_map);
        end
    end

end