classdef CMSMSPepDeconv
    properties
        m_modFile;          % Modification file path
        m_specPath;         % Path to the mixed spectra MGF file
        m_ms1_tolerance;    % Tolerance of MS1
        m_ms2_tolerance;    % Fragment ion matching tolerance
        m_alpha;            % Threshold for filtering noise peaks
        m_fastaFile;        % Absolute path to the FASTA file
        m_regular_express;  % The regular expression used for parsing protein name
        m_pepSpecFile;      % Input file name specifying some sequences and their corresponding spectra names
        m_model;            % Three models generated by three fragmentation efficiency assumptions: variable efficiency, constant but unequal efficiency, and efficiency of 1
        m_method;           % Estimation method, either ordinary least squares or with LASSO penalty
        m_lambda;           % LASSO penalty parameter
        m_resFilterThres;   % Threshold for filtering results by relative intensity
        m_enzyme;           % Enzyme used for digestion
        m_outputDir;        % Output folder
        m_checked_peptides_res_path; % File path for manually checked peptide results
        m_msms_res_path;    % File path for MSMS results
        m_ionTypes;         % Ion types used for matching

        m_fixedModNameMass;     % Specified fixed modifications: name, specificity, and mass
        m_variableModNameMass;  % Specified variable modifications: name, specificity, and mass
        m_cMgfDatasetIO;        % Record MGF spectra
        m_cMs12DatasetIO;       % Record MS1 and MS2 spectra
        m_cFastaIO;             % Record protein sequences database

        m_matFragInfo;      % Information of ions, three columns represent [b/y type, position, charge], each row is a fragment ion
        m_matFragEff;       % Fragmentation efficiency matrix of ions, each row corresponds to m_matFragInfo, each column is a solvable MS2 spectrum
        m_matFragIntens;    % Sum of experimental peak intensities of ions, each row corresponds to m_matFragInfo, each column is a solvable MS2 spectrum
    end

    methods
        function obj = CMSMSPepDeconv(modFile_or_taskparamobj,fixedMod,variableMod,...
                specPath,ms1_tolerance,ms2_tolerance,alpha,...
                fastaFile,regular_express,pepSpecFile,model,method,lambda,...
                resFilterThres,enzyme,outputDir,ionTypes,checked_peptides_res_path,msms_res_path)
            if nargin == 1
                % This is a method to read parameters from a .param file
                taskParam = modFile_or_taskparamobj;
                obj.m_specPath = taskParam.m_spec_dir_path;
                obj.m_modFile = taskParam.m_mod_file_path;
                obj.m_fastaFile = taskParam.m_fasta_file_path;
                obj.m_regular_express = taskParam.m_regular_express;
                obj.m_pepSpecFile = taskParam.m_pep_spec_file_path;
                obj.m_outputDir = taskParam.m_output_dir_path;
                obj.m_model = taskParam.m_model;
                obj.m_method = taskParam.m_method;
                obj.m_lambda = taskParam.m_lambda;
                obj.m_ms1_tolerance = taskParam.m_ms1_tolerance;
                obj.m_ms2_tolerance = taskParam.m_ms2_tolerance;
                obj.m_alpha = taskParam.m_alpha;
                obj.m_resFilterThres = taskParam.m_result_filter_threshold;
                obj.m_ionTypes = [1,2];
                obj.m_enzyme.name = taskParam.m_enzyme_name;
                obj.m_enzyme.limits = taskParam.m_enzyme_limits;
                obj.m_checked_peptides_res_path = taskParam.m_checked_peptides_res_path;
                obj.m_msms_res_path = taskParam.m_msms_res_path;
                % Generate variable modification "name-mass" dictionary using user-specified target modification strings and modification library
                mapModification = readModifyInfo(obj.m_modFile);
                obj.m_fixedModNameMass = obj.getModMassName(taskParam.m_fixed_mod,mapModification);
                obj.m_variableModNameMass = obj.getModMassName(taskParam.m_variable_mod,mapModification);
            else
                obj.m_specPath = specPath;
                obj.m_modFile = modFile_or_taskparamobj;
                obj.m_fastaFile = fastaFile;
                obj.m_regular_express = regular_express;
                obj.m_pepSpecFile = pepSpecFile;
                obj.m_model = model;
                obj.m_method = method;
                obj.m_lambda = lambda;
                obj.m_ms1_tolerance = ms1_tolerance;
                obj.m_ms2_tolerance = ms2_tolerance;
                obj.m_alpha = alpha;
                obj.m_resFilterThres = resFilterThres;
                obj.m_enzyme = enzyme;
                obj.m_outputDir = outputDir;
                if nargin >= 17
                    obj.m_ionTypes = ionTypes;
                end
                if nargin >= 18
                    obj.m_checked_peptides_res_path = checked_peptides_res_path;
                end
                if nargin == 19
                    obj.m_msms_res_path = msms_res_path;
                end
                % Generate variable modification "name-mass" dictionary using user-specified target modification strings and modification library
                mapModification = readModifyInfo(obj.m_modFile);
                obj.m_fixedModNameMass = obj.getModMassName(fixedMod,mapModification);
                obj.m_variableModNameMass = obj.getModMassName(variableMod,mapModification);
            end
        end

        % Check whether spectra names match
        check_whether_ms12_mgf_name_match(obj);

        % Run at MSMS level and peptide level
        obj = startRun(obj, is_record_fragment_information)

        % Generate modification "name-mass" list from user settings
        [modNameMass] = getModMassName(obj,modificationTypes,mapModification)

        % Re-quantify the IMPs using checked XIC peaks
        obj = requant(obj)

        % Re-quantify the normalization peptides using checked XIC peaks
        obj = requant_norm_pep(obj)

        % Draw the XIC for gathered peptides using manually-checked rt range, to dir_save
        % The color_map and legend_map are optional
        drawXIC(obj, dir_save, color_map, legend_map);
    end

end