function imp_records = appendRequantGroupRecord(obj, imp_records, group)
% Append re-quantification records for a single group
% Input:
%   obj (CIMPProcessingPipeline)
%       processing pipeline instance
%   imp_records (CIMPQuantRecord array)
%       accumulator for IMP records
%   group (CIMPGroup)
%       group payload for one raw and charge
% Output:
%   imp_records (CIMPQuantRecord array)
%       updated accumulator

if isempty(group.impRtRanges) || all(cellfun(@isempty, group.impRtRanges))
    return;
end

[has_nonzero_imp, imp_idx_nonzero, area_imp_final, xic_peak_rt_bounds, max_label, ratio_each_XIC_peak] = ...
    CIMPQuantifier.requantGroup(obj.m_ms12DatasetIO, group.rawName,...
    group.ratio(group.chargeGroupIdxs,:),...
    group.rts(group.chargeGroupIdxs,:),...
    group.intensity(group.chargeGroupIdxs,:),...
    group.lowMzBound, group.highMzBound, ...
    group.selectedCharge, group.impRtRanges,...
    obj.m_minMSMSnum);

if ~has_nonzero_imp
    return;
end
for i_iso = 1:length(imp_idx_nonzero)
    rt_peaks = struct(...
        'rt_start', xic_peak_rt_bounds(i_iso).rt_start, ...
        'rt_end', xic_peak_rt_bounds(i_iso).rt_end, ...
        'ratio', ratio_each_XIC_peak(i_iso), ...
        'check_label', max_label(i_iso));
    imp_records(end+1,1) = CIMPQuantRecord(...
        group.impNames{imp_idx_nonzero(i_iso)}, ...
        group.selectedCharge, ...
        group.rawName, ...
        mean([group.lowMzBound, group.highMzBound]), ...
        group.lowMzBound, ...
        group.highMzBound, ...
        area_imp_final(i_iso,1), ...
        rt_peaks); %#ok<AGROW>
end
end
