function cfg = fromParamMap(task_param_map)
% Build site-level dataset matrix config from parameter map.
% Inputs:
%   task_param_map (containers.Map)
%       Parameter key-value map for site-level dataset matrix summary.
% Outputs:
%   cfg (CSiteLevelDatasetPipelineConfig)
if ~isa(task_param_map, 'containers.Map')
    error('CSiteLevelDatasetPipelineConfig:InvalidParamMap', ...
        'Expected task_param_map to be a containers.Map.');
end

output_dir_path = CParamMapUtils.getOptional( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_OUTPUT_DIR_PATH, ...
    '', ...
    'CSiteLevelDatasetPipelineConfig');

if ~isempty(output_dir_path)
    CPathResolver.ensureDir(output_dir_path);
    input_default = fullfile(output_dir_path, 'report_peptide_all.txt');
    output_default = fullfile(output_dir_path, 'report_site_dataset_matrix.txt');
else
    input_default = '';
    output_default = '';
end

cfg_struct = struct();
cfg_struct.input_path = CParamMapUtils.getOptional( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_PEP_LEVEL_FILE_PATH, ...
    input_default, ...
    'CSiteLevelDatasetPipelineConfig');
cfg_struct.output_site_dataset_matrix_path = CParamMapUtils.getOptional( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_OUTPUT_SITE_DATASET_MATRIX_PATH, ...
    output_default, ...
    'CSiteLevelDatasetPipelineConfig');

protein_abbr_file_path = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_SITE_LEVEL_PROTEIN_ABBR_FILE_PATH, ...
    'site-level protein abbreviation map file path', ...
    'CSiteLevelDatasetPipelineConfig');
protein_abbr_file_col_protein_name = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_SITE_LEVEL_PROTEIN_ABBR_FILE_COL_PROTEIN_NAME, ...
    'site-level protein abbreviation file protein-name column', ...
    'CSiteLevelDatasetPipelineConfig');
protein_abbr_file_col_abbr_name = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_SITE_LEVEL_PROTEIN_ABBR_FILE_COL_ABBR_NAME, ...
    'site-level protein abbreviation file abbreviation column', ...
    'CSiteLevelDatasetPipelineConfig');

cfg_struct.protein_name_abbr = CSiteLevelPipelineConfig.loadProteinAbbrMapFromTsv( ...
    protein_abbr_file_path, ...
    protein_abbr_file_col_protein_name, ...
    protein_abbr_file_col_abbr_name);
cfg_struct.protein_abbr_file_path = protein_abbr_file_path;
cfg_struct.protein_abbr_file_col_protein_name = protein_abbr_file_col_protein_name;
cfg_struct.protein_abbr_file_col_abbr_name = protein_abbr_file_col_abbr_name;

mod_name_abbr_num = CParamMapUtils.getRequiredNumber( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_MOD_NAME_ABBR_NUM, ...
    'number of modification abbreviation mappings', ...
    'CSiteLevelDatasetPipelineConfig');
mod_name_abbr = containers.Map;
for idx = 1:mod_name_abbr_num
    key_name = [CPTMdecoderWorkflowParamKeys.PARAM_PREFIX_MOD_NAME_ABBR, num2str(idx)];
    pair_str = CParamMapUtils.getRequired( ...
        task_param_map, ...
        key_name, ...
        'modification abbreviation pair', ...
        'CSiteLevelDatasetPipelineConfig');
    split_str = strsplit(pair_str, '>');
    mod_name_abbr(strtrim(split_str{1})) = strtrim(split_str{2});
end
cfg_struct.mod_name_abbr = mod_name_abbr;

ignore_str = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_IGNORE_STRINGS_SITE_LEVEL, ...
    'ignore strings for site-level summary', ...
    'CSiteLevelDatasetPipelineConfig');
cfg_struct.ignore_strings = CParamMapUtils.parseQuotedList(ignore_str, ';');
cfg_struct.column_idxs = struct('icol_seq', 2, 'icol_dataset', 4, 'icol_auc', 8);

cfg = CSiteLevelDatasetPipelineConfig(cfg_struct);
end
