function cfg = fromParamMap(task_param_map)
% Build site-level dataset matrix config from parameter map.
% Inputs:
%   task_param_map (containers.Map)
%       Parameter key-value map for site-level dataset matrix summary.
% Outputs:
%   cfg (CSiteLevelDatasetPipelineConfig)
if ~isa(task_param_map, 'containers.Map')
    error('CSiteLevelDatasetPipelineConfig:InvalidParamMap', ...
        'Expected task_param_map to be a containers.Map.');
end

cfg_struct = struct();
cfg_struct.input_path = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_PEP_LEVEL_FILE_PATH, ...
    'peptide-level result file path', ...
    'CSiteLevelDatasetPipelineConfig');
cfg_struct.output_site_dataset_matrix_path = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_OUTPUT_SITE_DATASET_MATRIX_PATH, ...
    'output site-dataset matrix path', ...
    'CSiteLevelDatasetPipelineConfig');

mod_name_abbr_num = CParamMapUtils.getRequiredNumber( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_MOD_NAME_ABBR_NUM, ...
    'number of modification abbreviation mappings', ...
    'CSiteLevelDatasetPipelineConfig');
mod_name_abbr = containers.Map;
for idx = 1:mod_name_abbr_num
    key_name = [CPTMdecoderWorkflowParamKeys.PARAM_PREFIX_MOD_NAME_ABBR, num2str(idx)];
    pair_str = CParamMapUtils.getRequired( ...
        task_param_map, ...
        key_name, ...
        'modification abbreviation pair', ...
        'CSiteLevelDatasetPipelineConfig');
    split_str = strsplit(pair_str, '>');
    mod_name_abbr(strtrim(split_str{1})) = strtrim(split_str{2});
end
cfg_struct.mod_name_abbr = mod_name_abbr;

ignore_str = CParamMapUtils.getRequired( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_IGNORE_STRINGS_SITE_LEVEL, ...
    'ignore strings for site-level summary', ...
    'CSiteLevelDatasetPipelineConfig');
cfg_struct.ignore_strings = CParamMapUtils.parseQuotedList(ignore_str, ';');
cfg_struct.site_position_count_initial_m = CParamMapUtils.getOptionalLogical( ...
    task_param_map, ...
    CPTMdecoderWorkflowParamKeys.PARAM_SITE_POSITION_COUNT_INITIAL_M, ...
    true, ...
    'CSiteLevelDatasetPipelineConfig');
cfg_struct.column_idxs = struct('icol_seq', 2, 'icol_dataset', 4, 'icol_auc', 8);

cfg = CSiteLevelDatasetPipelineConfig(cfg_struct);
end
