classdef CPTMdecoderWorkflowParamKeys
    % Parameter key constants for PTMdecoder workflow and stage config builders.

    properties (Constant)
        PARAM_MSMS_PEPTIDE_LEVEL_ON = 'msms_peptide_level_on'
        PARAM_MSMS_ONLY_ON = 'msms_only_on'
        PARAM_PEPTIDE_ONLY_ON = 'peptide_only_on'
        PARAM_PEPTIDE_REQUANT_ON = 'peptide_requant_on'
        PARAM_PEPTIDE_ALIGN_REQUANT_ON = 'peptide_align_requant_on'
        PARAM_NORM_PEPTIDE_QUANT_ON = 'norm_peptide_quant_on'
        PARAM_NORM_PEPTIDE_REQUANT_ON = 'norm_peptide_requant_on'
        PARAM_SITE_LEVEL_ON = 'site_level_on'
        PARAM_SITE_LEVEL_DATASET_ON = 'site_level_dataset_on'
        PARAM_MERGE_TO_PAIR_LEVEL_ON = 'merge_to_pair_level_on'
        PARAM_MERGE_PAIRS_LEVEL_ON = 'merge_pairs_level_on'

        PARAM_MOD_FILE_PATH = 'mod_file_path'
        PARAM_FIXED_MOD = 'fixed_mod'
        PARAM_VARIABLE_MOD = 'variable_mod'
        PARAM_SPEC_DIR_PATH = 'spec_dir_path'
        PARAM_MS1_TOLERANCE_VALUE = 'ms1_tolerance_value'
        PARAM_MS1_TOLERANCE_TYPE = 'ms1_tolerance_type'
        PARAM_MS2_TOLERANCE = 'ms2_tolerance'
        PARAM_ALPHA = 'alpha'
        PARAM_FASTA_FILE_PATH = 'fasta_file_path'
        PARAM_REGULAR_EXPRESS = 'regular_express'
        PARAM_FILTERED_RES_FILE_PATH = 'filtered_res_file_path'
        PARAM_MODEL = 'model'
        PARAM_METHOD = 'method'
        PARAM_LAMBDA = 'lambda'
        PARAM_RESULT_FILTER_THRESHOLD = 'result_filter_threshold'
        PARAM_N_RESAMPLES = 'n_resamples'
        PARAM_RANDOM_SEED = 'random_seed'
        PARAM_STABILITY_PARALLEL_ON = 'stability_parallel_on'
        PARAM_ENZYME_NAME = 'enzyme_name'
        PARAM_ENZYME_LIMIT_C_TERM_POSSIBLE_MOD = 'enzyme_limit_C_term_possible_mod'
        PARAM_OUTPUT_DIR_PATH = 'output_dir_path'
        PARAM_MIN_MSMS_NUM = 'min_MSMS_num'
        PARAM_PEPTIDE_MIN_LENGTH = 'peptide_min_length'
        PARAM_PEPTIDE_MAX_LENGTH = 'peptide_max_length'
        PARAM_MAX_MOD_PER_PEPTIDE = 'max_mod_per_peptide'
        PARAM_PEP_SPEC_FILE_PATH = 'pep_spec_file_path'
        PARAM_CHECKED_PEPTIDES_RES_PATH = 'checked_peptides_res_path'
        PARAM_MSMS_RES_PATH = 'msms_res_path'
        PARAM_PEPTIDE_QUANT_STABILITY_FILTER_ON = 'peptide_quant_stability_filter_on'
        PARAM_PEPTIDE_QUANT_MIN_JACCARD_STABILITY = 'peptide_quant_min_jaccard_stability'
        PARAM_PEPTIDE_QUANT_MIN_SUPPORT_FREQUENCY = 'peptide_quant_min_support_frequency'
        PARAM_PEPTIDE_QUANT_MAX_ABUNDANCE_MAD = 'peptide_quant_max_abundance_mad'
        PARAM_PEPTIDE_QUANT_STABILITY_NAN_AS_FAIL = 'peptide_quant_stability_nan_as_fail'
        PARAM_ALIGN_STRATEGY_TYPE = 'align_strategy_type'
        PARAM_ALIGN_REFERENCE_RAW = 'align_reference_raw'
        PARAM_ALIGN_PAIR_NUM = 'align_pair_num'
        PARAM_PREFIX_ALIGN_PAIR = 'align_pair_'
        PARAM_ALIGN_MIN_PSM = 'align_min_psm'
        PARAM_ALIGN_NUM_BINS = 'align_num_bins'
        PARAM_ALIGN_MIN_PER_BIN = 'align_min_per_bin'
        PARAM_ALIGN_OUTLIER_K = 'align_outlier_k'
        PARAM_ALIGN_OUTLIER_METHOD = 'align_outlier_method'
        PARAM_ALIGN_RT_SIGMA = 'align_rt_sigma'
        PARAM_ALIGN_MAX_RT_RESIDUAL = 'align_max_rt_residual'
        PARAM_ALIGN_DEAD_TIME_MIN = 'align_dead_time_min'
        PARAM_ALIGN_REPORT_PATH = 'align_report_path'
        PARAM_ALIGN_REQUANT_OUTPUT_PATH = 'align_requant_output_path'
        PARAM_NORM_PROTEIN_PEPTIDE_PAIR_PATH = 'norm_protein_peptide_pair_path'
        PARAM_NORM_OUTPUT_FILE_NAME = 'norm_output_file_name'
        PARAM_NORM_REQUANT_OUTPUT_FILE_NAME = 'norm_requant_output_file_name'

        PARAM_PEP_LEVEL_FILE_PATH = 'pep_level_file_path'
        PARAM_OUTPUT_INTERE_PATH = 'output_intere_path'
        PARAM_OUTPUT_UNINTERE_PATH = 'output_unintere_path'
        PARAM_OUTPUT_SITE_DATASET_MATRIX_PATH = 'output_site_dataset_matrix_path'
        PARAM_SITE_POSITION_COUNT_INITIAL_M = 'site_position_count_initial_m'
        PARAM_SITE_LEVEL_DATASET_PROTEIN_NAME_REGEX = 'site_level_dataset_protein_name_regex'
        PARAM_SITE_LEVEL_PROTEIN_ABBR_INPUT_MODE = 'site_level_protein_abbr_input_mode'
        PARAM_SITE_LEVEL_PROTEIN_ABBR_FILE_PATH = 'site_level_protein_abbr_file_path'
        PARAM_SITE_LEVEL_PROTEIN_ABBR_FILE_COL_PROTEIN_NAME = 'site_level_protein_abbr_file_col_protein_name'
        PARAM_SITE_LEVEL_PROTEIN_ABBR_FILE_COL_ABBR_NAME = 'site_level_protein_abbr_file_col_abbr_name'
        PARAM_PROTEIN_NAME_ABBR_NUM = 'protein_name_abbr_num'
        PARAM_MOD_NAME_ABBR_NUM = 'mod_name_abbr_num'
        PARAM_IGNORE_STRINGS_SITE_LEVEL = 'ignore_strings_site_level'

        PARAM_LEFT_RIGHT_OUT_NUM = 'left_right_out_num'
        PARAM_LEFT_NAME = 'left_name'
        PARAM_RIGHT_NAME = 'right_name'
        PARAM_IGNORE_STRINGS_PAIR_LEVEL = 'ignore_strings_pair_level'

        PARAM_PAIR_NUM = 'pair_num'
        PARAM_FINAL_OUTPUT_PATH = 'final_output_path'

        PARAM_PREFIX_PROTEIN_NAME_ABBR = 'protein_name_abbr_'
        PARAM_PREFIX_MOD_NAME_ABBR = 'mod_name_abbr_'
        PARAM_PREFIX_LEFT_RIGHT_OUT = 'left_right_out_'
        PARAM_PREFIX_PAIR = 'pair_'
        PARAM_PREFIX_LEFT_RIGHT_NAME = 'left_right_name_'

        PARAM_LOG_ENABLED = 'log_enabled'
        PARAM_LOG_FILE_DIR = 'log_file_dir'
        PARAM_LOG_FILE_LEVEL = 'log_file_level'
        PARAM_LOG_TO_CONSOLE = 'log_to_console'
        PARAM_LOG_CONSOLE_LEVEL = 'log_console_level'
    end
end
