function block = requantifyIMPsWithRTRanges(obj,pep_rtrange_map)
% Re-quantification for gathered peptides using manually-checked rt range
% Input:
%   obj (CIMPGatherQuant)
%       Quantification aggregator instance
%   pep_rtrange_map (containers.Map)
%       map of [modified peptide _ charge _ raw file name] -> [rt_start, rt_end, check_label]
% Output:
%   block (CIMPQuantBlock or empty)
%       Protein block with IMP records, empty if no records

imp_records = CIMPQuantRecord.empty(0,1);

% Do the same operation for gathered PSM for every raw file
[raw_names, raw_ident_stores] = obj.getRawEntries();
for idx_raw = 1:numel(raw_names)
    imp_records = obj.m_groupAggregator.aggregate(raw_names{idx_raw}, raw_ident_stores{idx_raw}, pep_rtrange_map, ...
        @(state, group) handle_group_charge(state, obj, group), imp_records);
end
if isempty(imp_records)
    block = CIMPQuantBlock.empty(0,1);
else
    block = CIMPQuantBlock(obj.m_prot_names_pos, imp_records);
end
end



function imp_records = handle_group_charge(imp_records, obj, group)
if isempty(group.impRtRanges) || all(cellfun(@isempty, group.impRtRanges))
    % All of the IMPs are removed in manual checking
    return;
end

% group quant
[has_nonzero_imp, imp_idx_nonzero, area_imp_final, xic_peak_rt_bounds, max_label, ratio_each_XIC_peak] = ...
    CIMPQuantifier.requantGroup(obj.m_cMs12DatasetIO, group.rawName,...
    group.ratio(group.chargeGroupIdxs,:),...
    group.rts(group.chargeGroupIdxs,:),...
    group.intensity(group.chargeGroupIdxs,:),...
    group.lowMzBound, group.highMzBound, ...
    group.selectedCharge, group.impRtRanges,...
    obj.m_minMSMSnum);

% Only record the non-zero result
if ~has_nonzero_imp
    return;
end
for i_iso = 1:length(imp_idx_nonzero)
    rt_peaks = struct(...
        'rt_start', xic_peak_rt_bounds(i_iso).rt_start, ...
        'rt_end', xic_peak_rt_bounds(i_iso).rt_end, ...
        'ratio', ratio_each_XIC_peak(i_iso), ...
        'check_label', max_label(i_iso));
    imp_records(end+1,1) = CIMPQuantRecord(...
        group.impNames{imp_idx_nonzero(i_iso)}, ...
        group.selectedCharge, ...
        group.rawName, ...
        mean([group.lowMzBound, group.highMzBound]), ...
        group.lowMzBound, ...
        group.highMzBound, ...
        area_imp_final(i_iso,1), ...
        rt_peaks); %#ok<AGROW>
end
end
