function rerunGather_quant(obj,pep_rtrange_map)
% Re-quantification for gathered peptides using manually-checked rt range
% Input:
%   obj (CIMPGatherQuant)
%       Quantification aggregator instance
%   pep_rtrange_map (containers.Map)
%       map of [modified peptide _ charge _ raw file name] -> [rt_start, rt_end, check_label]

imp_records = repmat(struct('imp_name','', 'charge',0, 'raw_name','', ...
    'mass_center',0, 'low_mz_bound',0, 'high_mz_bound',0, 'area',0, ...
    'rt_peaks',struct('start',{},'end',{},'ratio',{},'check_label',{})), 0, 1);


% Do the same operation for gathered PSM for every raw file
imp_records = iterate_imp_groups(obj, pep_rtrange_map, @handle_group_charge, imp_records);
CIMPGatherWriter.write_imp_group_block(obj.m_outputPath, obj.m_prot_names_pos, imp_records);
end



function imp_records = handle_group_charge(imp_records, obj, raw_name, group_imp_name, group_ratio, group_rts, group_inten, ...
        ~, low_mz_bound, high_mz_bound, selected_charge, charge_group_idxs, current_imp_rt_range)
if isempty(current_imp_rt_range) || all(cellfun(@isempty,current_imp_rt_range))
    % All of the IMPs are removed in manual checking
    return;
end

% group quant
[has_nonzero_imp, imp_idx_nonzero, area_imp_final, rt_bound, max_label, ratio_each_XIC_peak] = ...
    obj.requant_each_group(raw_name,...
    group_ratio(charge_group_idxs,:),...
    group_rts(charge_group_idxs,:),...
    group_inten(charge_group_idxs,:),...
    low_mz_bound,high_mz_bound, ...
    selected_charge,current_imp_rt_range);

% Only record the non-zero result
if ~has_nonzero_imp
    return;
end
for i_iso = 1:length(imp_idx_nonzero)
    rt_peaks = struct(...
        'start', rt_bound(i_iso).start, ...
        'end', rt_bound(i_iso).end, ...
        'ratio', ratio_each_XIC_peak(i_iso), ...
        'check_label', max_label(i_iso));
    imp_records(end+1,1) = struct(...
        'imp_name', group_imp_name{imp_idx_nonzero(i_iso)}, ...
        'charge', selected_charge, ...
        'raw_name', raw_name, ...
        'mass_center', mean([low_mz_bound,high_mz_bound]), ...
        'low_mz_bound', low_mz_bound, ...
        'high_mz_bound', high_mz_bound, ...
        'area', area_imp_final(i_iso,1), ...
        'rt_peaks', rt_peaks); %#ok<AGROW>
end
end