function rerunGather_quant(obj,pep_rtrange_map)
% Re-quantification for gathered peptides using manually-checked rt range
% Input:
%   obj (CIMPGatherQuant)
%       Quantification aggregator instance
%   pep_rtrange_map (containers.Map)
%       map of [modified peptide _ charge _ raw file name] -> [rt_start, rt_end, check_label]

imp_records = CIMPQuantResult.empty(0,1);


% Do the same operation for gathered PSM for every raw file
imp_records = iterate_imp_groups(obj, pep_rtrange_map, @handle_group_charge, imp_records);
CIMPGatherWriter.write_imp_group_block(obj.m_outputPath, obj.m_prot_names_pos, imp_records);
end



function imp_records = handle_group_charge(imp_records, obj, group)
if isempty(group.impRtRanges) || all(cellfun(@isempty, group.impRtRanges))
    % All of the IMPs are removed in manual checking
    return;
end

% group quant
[has_nonzero_imp, imp_idx_nonzero, area_imp_final, rt_bound, max_label, ratio_each_XIC_peak] = ...
    obj.requant_each_group(group.rawName,...
    group.ratio(group.chargeGroupIdxs,:),...
    group.rts(group.chargeGroupIdxs,:),...
    group.intensity(group.chargeGroupIdxs,:),...
    group.lowMzBound, group.highMzBound, ...
    group.selectedCharge, group.impRtRanges);

% Only record the non-zero result
if ~has_nonzero_imp
    return;
end
for i_iso = 1:length(imp_idx_nonzero)
    rt_peaks = struct(...
        'start', rt_bound(i_iso).start, ...
        'end', rt_bound(i_iso).end, ...
        'ratio', ratio_each_XIC_peak(i_iso), ...
        'check_label', max_label(i_iso));
    imp_records(end+1,1) = CIMPQuantResult(...
        group.impNames{imp_idx_nonzero(i_iso)}, ...
        group.selectedCharge, ...
        group.rawName, ...
        mean([group.lowMzBound, group.highMzBound]), ...
        group.lowMzBound, ...
        group.highMzBound, ...
        area_imp_final(i_iso,1), ...
        rt_peaks); %#ok<AGROW>
end
end